version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
